"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./(components)/Header/Header";
import Footer from "./(components)/Footer/Footer";
import StoreProvider, { useAppSelector } from "./redux";
import { ToastContainer } from "react-toastify";
import ChatBot from "./(components)/ChatBot/ChatBot";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "NS HeathCare",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const standaloneRoutes = ["/login", "/register"];

  const isStandalonePage = standaloneRoutes.includes(pathname);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <StoreProvider>
        {isStandalonePage ? (
          children
        ) : (
          <div className="md:px-20 ">
            <Header />
            {children}
            <ChatBot />
            <Footer />
          </div>
          )}
        </StoreProvider>
      </body>
    </html>
  );
}
